Adds navigation buttons
sbailey/viproto-inspector pull request #8
Opened 2018-07-27 23:29 UTC by sbailey

This PR:
* Adds navigation buttons for previous/next (instead of having to call `.prev()` and `.next()` in separate cells
* Adds buttons for saving visual scan results + advancing to next target
* Updates the layout so that everything fits within the width of a juypter window at NERSC without scrolling

See the inspector.ipynb notebook for examples on running this.

This code is definitely getting to need a cleanup pass; this PR is *not* that.

2018-07-30 21:54 UTC, weaverba137 requested changes
The code looks fine but there is one significant problem I found with the buttons:  There is a small X to the left of the buttons, and if you click it, the buttons disappear, and there is no obvious way to get them back.  If possible, eliminate this "close" button so that the buttons can't be lost due to an accidental click.

2018-08-03 17:36 UTC, sbailey commented
Good suggestion.  Oddly the "X" button appears at NERSC but not on my laptop.

This stack overflow post may have the necessary ingredients to fix this, but I haven't put all the pieces together yet: https://stackoverflow.com/questions/42155210/how-can-i-remove-or-disable-an-ipywidgets-widget-clear-button-in-a-jupyter-note .  Posting it here so that I don't lose this link (took me awhile to figure out the right keywords to search for...)  I'll keep working on it.

2018-08-03 18:11 UTC, sbailey commented
The close button of the navigation widgets is now disabled.  @weaverba137 please check that it also works for you.

Adapted from https://groups.google.com/forum/#!topic/jupyter/r67iMlSmuEg
```
hideclose = "<script>$('.widget-area .prompt .close').hide()</script>"
display(HTML(hideclose))
```

2018-08-03 20:38 UTC, weaverba137 approved these changes

2018-08-03 20:38 UTC, weaverba137 commented
Confirmed that the close button is gone and also tested the flag functionality.  Merge when ready.

2018-08-03 20:48 UTC, merged